model:
  name: classical_lgbm

features:
  hog_size: 128
  orientations: 9
  pixels_per_cell: 8
  cells_per_block: 2

training:
  use_gpu: false
  param_grid:
    num_leaves: [31]
    learning_rate: [0.1]
    n_estimators: [100]
  subsample: 0.8
  colsample_bytree: 0.8
