model:
  name: vit
  pretrained: true

training:
  epochs: 12
  freeze_epochs: 2
  batch_size: 16
  lr: 0.0001
  unfreeze_lr: 0.00005
  weight_decay: 0.0001
  optimizer: adam

data:
  img_size: 128
  aug: 1
